### ISSUE TITLE
Sozi 16.02 Layers disappear 

### ISSUE THREAD

**Issue by AntonKolganov** [senshu/Sozi#374] opened 2016-09-08 06:24 UTC
I use Sozi in Win 10 64bit environment. Everything works well. But sometimes some layers disappear from final presentation in HTML, i.e. I see the layers in Sozi but after saving the presentation I can not see them.
Please see screenshots
http://joxi.ru/52ayKVYInn0820
http://joxi.ru/L21lwVbUJJVzmX
http://joxi.ru/n2YBEj5HOOVPA6

The only way to resolve the problem is to make presentation from zero.

**Comment by AntonKolganov** [comment] 2016-09-08 06:49
One moment I have observed the problem appears after initial SVG file reloading in Sozi. For example I change some little things in SVG file without touching layers and reload it in Sozi after the changing.

**Comment by Supermanu** [comment] 2016-10-14 18:04
I can confirm this behaviour with Archlinux. I use Inkscape to modify the SVG file.

**Comment by Benjou** [comment] 2017-04-17 09:19
I can confirm the bug. 
Quite annoying. I have a layer with objects that I show and hide at need.

At the beginning of the presentation, everything looks fine. After a while, trying to move that layer will make it disappear entirely both in Sozi-editor, and in Firefox.

I'm using both Sozi and inkscape on Mac or on Ubuntu. I've been using both Sozi 16 and 17. The problem is with all versions, all systems and all browsers so far.

When re-making the same presentation (almost) from scratch (i.e. use the same svg file, but delete the json file) makes me run into the same problem.

Any idea what is going on and how to solve it?

thanks!

**Comment by senshu** [comment] 2017-04-17 14:25
It would be great if you could send me an example presentation (SVG + JSON) that illustrates the issue.
Please explain what actions you did to edit that document until you observed the problem.

**Comment by Benjou** [comment] 2017-04-25 08:31
Dear Guillaume,

Sorry for the late answer.

I'd be happy to send you the presentation, but I'd rather not post it on the internet.
Could you contact me at benoit dot kornmann at gmail dot com?

**Comment by senshu** [comment] 2017-05-29 20:49
Sozi 17.05.292235 provides a partial solution to this issue.

To make things clearer, layers do not really "disappear" but they are in an invalid state. For instance, their zoom factor becomes infinite. I still don't know which sequence of actions produce the problem, but when it happens, the button "Reset layer geometry" can help you recover. It will simply reset the scale, translation and rotation of the selected layers as they were in the original SVG.

You can download the latest development version from: https://drive.google.com/drive/folders/0ByRUreHgekjMWG9teGM2dE8wck0?usp=sharing

**Comment by clement-moulin-frier** [comment] 2017-05-29 22:16
Hi,
I don't see the version 17.05.292235 in the google drive (last one is 17.05.271506). Maybe you forgot to upload it?
I'm gonna try to get a minimal example of the problem I've experienced and come back to you soon.
Thanks,

**Comment by senshu** [comment] 2017-05-30 04:48
The upload was interrupted. Trying again.

**Comment by clement-moulin-frier** [comment] 2017-05-30 09:13
Sorry but there is only the darwin version available, no linux.

**Comment by senshu** [comment] 2017-05-30 16:45
The Linux version is available for download. Sorry for the inconvenience.

**Comment by senshu** [comment] 2019-05-21 11:18
Closing the issue. Please feel free to reopen it if you can provide a scenario to reproduce the problem.

**Closed by senshu** 2019-05-21 11:18 UTC
Labels: bug, in progress
