### ISSUE TITLE
Really slow Editor on 20-th frame

### ISSUE THREAD

**Issue by as3mbus** [senshu/Sozi#424] opened 2018-03-04 16:15 UTC
### Summary of your problem or feature request

i'm having huge pause every time i move, scale, rotate the camera on sozi editor, (is it possible that it caused by imported image with link ?)  

### Version of Sozi and other relevant software

* Which version of Sozi are you using? 18.01 Linux 64 bit tar package
* Which drawing software did you use? (Inkscape 0.92.2
* On which platform? Arch Linux 64 Bit
* If your problem happens when playing a presentation, which browsers have you tried? nope. but played on firefox fine (Firefox Nightly 60.0.a1)

### Steps to reproduce the problem

1. create inkscape file with quite many many imported image using link method
2. run sozi 
3. create simple frame which transistion is only move, zoom and crop
4. it getting slower on every frame i made, on 20th~ frame it take a few second to somewhat reload (it feels like sozi freeze for a moment) after moving, zooming, the camera.
5. i ended up waiting for 5+ sec after 30~frames.
6. tested to play the presentation on firefox plays fine and smooth

### Expected behavior

response faster after every camera navigation

### Observed behavior

several second delay after every navigation

### Hints and solutions (optional)

it might be caused by linked image ?
if it is, it might be good to mention that in the page.....

**Comment by senshu** [comment] 2018-03-09 20:27
> tested to play the presentation on firefox plays fine and smooth

This is interesting. The editor and player use the same code, so I would expect similar issues with Firefox. Since the editor is based on Chromium, it would be useful to check whether the presentations plays smoothly in Chromium or Chrome as well.

What is the size of the images?
Do you observe similar issues if the images are not linked, but embedded in the SVG?

**Comment by as3mbus** [comment] 2018-03-11 16:22
### What is the size of the images?
around 100-200kb each
and there are around 10 -15 image.

### Do you observe similar issues if the images are not linked, but embedded in the SVG?
havent tested yet

### additional information
https://github.com/as3mbus/Linux_Desktop
this is the presentation file including images.
i'll try to mess around with chrome and stuff later

**Comment by Ekinoks** [comment] 2019-02-11 19:39
I have exactly the same problem, if the presentation have too many frames, then after each move or resize Sozi freeze during 5-10 sec.

**Comment by senshu** [comment] 2019-02-12 07:47
@Ekinoks Can you, please, try Sozi 18.11 from https://drive.google.com/drive/folders/0ByRUreHgekjMWG9teGM2dE8wck0 and tell me if it works better in your case?

**Comment by Ekinoks** [comment] 2019-02-12 17:13
@senshu It may be a little better with version 18.11.25 but I still have freezes of several seconds.
It is as if after applying a movement, the software rewrites all the code causing the freeze.
PS: I forgot to say, I'm on Windows

**Comment by h4de5** [comment] 2019-03-05 21:40
Same here - i am on current nightly - 18.11.25
I am using images that have several MBs also linked. also note, that the moving/resizing of the layers itself is running smoothly, but as soon as i release that layer or stop resizing it, it freezes for like 5 seconds.

**Comment by senshu** [comment] 2019-03-06 20:54
@h4de5 The issue is difficult to reproduce. I think that it happens when you change the SVG multiple times while it is open in Sozi. Usually, when it becomes unusable, a workaround is to close Sozi and reopen it.

I have just pushed a fix for a problem that could be related to this issue. See commit 037fe90e676e4494bfa48d87d466fc2e4a3bdea1
I will upload a new test release tonight, please check [the Sozi nightly builds folder](https://drive.google.com/drive/folders/0ByRUreHgekjMWG9teGM2dE8wck0). The new version number will be 19.03.

**Comment by h4de5** [comment] 2019-03-11 01:54
I can confirm that this issue comes from changing the svg outside of sozi while it has it open.
i worked now for several hours with normals saves and moves .. and it did not occure again.

will try out the new version soon.

**Closed** 2019-05-21 09:25 UTC
Labels: done
