### ISSUE TITLE
Sozi click handler breaks hyperlinks

### ISSUE THREAD

**Issue by davidchisnall** [senshu/Sozi#314] opened 2015-09-02 16:50 UTC
If I have a hyperlink (`<a xlink:href="..."><text>...</text></a>`) in my SVG file, it is no longer clickable in the Sozi-generated file.  The Sozi JavaScript should ideally only hijack clicks that are not on an element that already has some onclick behaviour.

**Comment by senshu** [comment] 2015-09-03 20:36
I cannot reproduce the issue. Hyperlinks work as expected for me.
Actually, Sozi does not hijack clicks on hyperlinks.

**Comment by davidchisnall** [comment] 2015-09-04 08:30
Interesting.  It works fine in Firefox - clicking on the link navigates to the target.  In Chromium, Sozi handles the click and begins the animation, but the navigation also happens.  In Safari, only Sozi gets the click and the navigation doesn't happen.

**Comment by senshu** [comment] 2015-10-04 09:51
OK. Now I understand that the bug concerns links to **external** URLs.
Links to other frames in the current presentation work as expected.

I can reproduce the issue in Firefox as well: setting `_new` as the link target allows the animation to run in the current browser tab while the target site opens in another tab.

**Comment by senshu** [comment] 2015-10-04 10:16
I have pushed a fix that works in Firefox and Chromium. Please tell me if it works in Safari as well.

**Closed** 2015-10-04 10:17 UTC

**Comment by davidchisnall** [comment] 2015-10-05 09:01
Any chance of a new release with these fixes?

**Comment by senshu** [comment] 2015-10-05 11:53
A *nightly release* is available here https://drive.google.com/open?id=0ByRUreHgekjMWG9teGM2dE8wck0

**Comment by davidchisnall** [comment] 2015-10-05 16:54
Thanks.  The links now work if I click on them in Safari.  Right clicking on them (to bring up the context menu) jumps back to the previous slide.  Command-click (open in new tab) is somewhat unreliable - it only works if I press command after moving the mouse to the link.
