### ISSUE TITLE
insert Video ? no effect

### ISSUE THREAD

**Issue by choralou** [senshu/Sozi#378] opened 2016-11-26 11:03 UTC
HI
On Ubutu 16.04 no video with sozi 
Firefox ca read the video.webm himself
The file video.webm is in the same path as the file.svg
the name of path 
 i try ./video.webm not work
i try file:///home/dan/Documents/sozi/cideo.wbm not work
Only the same gray rectangle on the file.svg and in firefoxHelp !
Tanks
Daniel

**Comment by senshu** [comment] 2017-01-28 13:20
Can you please send an example document that could help me reproduce the issue?

**Comment by senshu** [comment] 2017-12-03 11:05
@choralou I'm closing this issue since you did not provide the information that could help me solve your problem. Please feel free to reopen it if you think it is still relevant.

**Closed by senshu** 2017-12-03 11:05 UTC
Labels: bug, unconfirmed

**Comment by HansAchterbahn** [comment] 2017-12-04 16:37
I  have the same problem with Ubuntu 17.10 and Firefox 56.0

**Comment by senshu** [comment] 2017-12-04 17:47
@HansAchterbahn Please see the comment I wrote on January 28 2016. I cannot help you if you don't provide more details.

**Comment by senshu** [comment] 2017-12-04 18:02
@HansAchterbahn Also, please open a new issue for your specific situation. I usually don't keep track of closed issues and I will probably forget it.
