### ISSUE TITLE
Sozi-15.11.210709 slow zooming regression

### ISSUE THREAD

**Issue by sunaku** [senshu/Sozi#341] opened 2016-02-03 05:06 UTC
Hello,

Sozi-15.11.210709 introduced a regression that causes zooming to slow down significantly (more than 5 seconds per zoom operation via mouse wheel scroll).  :scream: This problem does not happen under the previous release Sozi-15.06.302155, even on large (3 MB) SVG files full of complex calligraphy strokes. :ghost:

Thanks for your consideration.

**Comment by sunaku** [comment] 2016-02-06 02:43
I'm currently working around this problem by:

1. Use the _previous_ :ghost: Sozi-15.06.302155-linux64 release to develop my slideshow.
2. At the very :end: (when you're ready to produce the final HTML output) open your Sozi project in the latest Sozi-15.11.210709 release. :open_file_folder: Note that simply opening the project is enough for Sozi to re-generate the HTML output! :sparkles: 
3. Close :facepunch: the Sozi window opened in step 2.

**Comment by miguel-negrao** [comment] 2016-05-05 14:25
This issue is still present in 16.02 , using 15.06 there is no issue with zooming.

**Comment by Gotisch** [comment] 2017-05-01 20:54
still present in Sozi-17.02.072116 (linux x64)

**Comment by senshu** [comment] 2018-05-28 21:05
@sunaku observed a regression between Sozi 15.06 and Sozi 15.11. After comparing those versions, I did not find any difference in Sozi itself that could explain the regression. The only difference that could be related was a change in the version of NW.js that was used at the time.

It seems that users are still observing a similar issue in Sozi 18.
Since Sozi 18 is no longer based on NW.js, I cannot confirm that the problem is the same.

At the moment, I cannot fix the issue because I have never observed it myself.
To fix this issue, I need an example document that could help me reproduce the problem.
I also need a detailed description of all the steps that I need to perform.

**Comment by senshu** [comment] 2018-06-12 19:12
> Don't know what else to tell you there, in my case it would be to just open the svg in sozi.

@amk1208 Do you mean that the problem occurs immediately after opening the document?

I think I remember someone reporting that Sozi becomes slower after reloading the SVG repeatedly. The workaround was to close and reopen Sozi.

**Comment by amk1208** [comment] 2018-06-14 05:13
Hi,
thanks for getting back.
After closing and reopening sozi I can selecting a frame is working again smoothly.
But for moving oder zooming it doesn’t help. Neither in 15.6 nor 17.
Cheers.

**Comment by senshu** [comment] 2019-05-21 09:28
Should be fixed in Sozi 19.04.

**Closed** 2019-05-21 09:28 UTC
Labels: bug, unconfirmed
