### ISSUE TITLE
Sozi 15 - Wont load large images

### ISSUE THREAD

**Issue by joha1** [senshu/Sozi#292] opened 2015-05-21 14:07 UTC
While searching around for the solution for my other issue, I found out that 13 is going to be phased out, and 15 is the new thing.

Great - apart from the fact that its really hard to use without any documentation (but that is already planned to be changed, if I read the site correctly) - it looks really promising!

The presentation I tried to start, features, among other things, a large (10000x15000,7MB) image, on which I want to move around, highlighting certain parts of it.

But the editor will not show that image. When trying to zoom out to find the parts I want to frame, the UI starts to lag, I get 100% CPU load, and after everything settled, and I see my zoomed out canvas, the image wont show up, whereas some other, much smaller elements do show up.

The output in terminal doesnt tell me much:

```
[me@localhost Sozi-15.05.142313-linux64]$ ./Sozi 
[4441:0521/145243:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
 ATTENTION: default value of option force_s3tc_enable overridden by environment.
[4441:0521/145244:INFO:CONSOLE(1)] ""Configuration in: /home/johannes/.config/Sozi"", source: file:///tmp/.org.chromium.Chromium.G7g0lR/js/editor.min.js (1)
[4441:0521/145244:INFO:CONSOLE(1)] ""Current working dir: /home/johannes/bin/Sozi-15.05.142313-linux64"", source: file:///tmp/.org.chromium.Chromium.G7g0lR/js/editor.min.js (1)
[4441:0521/145245:ERROR:nw_shell.cc(335)] TypeError: Cannot read property 'setAttribute' of undefined
    at d.l.repaint (file:///tmp/.org.chromium.Chromium.G7g0lR/js/editor.min.js:3:6161)
    at Object.e.onMouseEnter (file:///tmp/.org.chromium.Chromium.G7g0lR/js/editor.min.js:3:11100)
[4441:0521/145245:INFO:CONSOLE(3)] "Uncaught TypeError: Cannot read property 'setAttribute' of undefined", source: file:///tmp/.org.chromium.Chromium.G7g0lR/js/editor.min.js (3)
[4469:0521/150100:ERROR:channel.cc(305)] RawChannel read error (connection broken)
[me@localhost Sozi-15.05.142313-linux64]$ Failed to tell parent about crash.
^C
```

Maybe also of interes: after closing the sozi window, I get the `Failed to tell parent about crash.` thing in terminal, so I quit that with ctrl+c.

**Comment by senshu** [comment] 2015-05-25 19:23
When you load the original SVG in a web browser, is the image correctly displayed? Do you notice a long loading time?

**Comment by joha1** [comment] 2015-05-26 08:23
>long loading time
Well, that's kinda subjective, but I would consider it kinda long, with some high CPU utilisation. As expected, since it is indeed somewhat big.

>is the image correctly displayed?
No. its also gone, it seems. But in inkscape it does show up. 

As said, it is a big file, but just "ignoring" it without any visible errors seems kinda weird.

**Comment by senshu** [comment] 2015-05-26 08:29
> No. its also gone, it seems.

So, the bug is not in Sozi itself.
Can you send me a sample document that illustrates the issue?

**Comment by senshu** [comment] 2015-06-06 09:16
I could not reproduce the issue. I have created a large image, the same size as yours. My document loads correctly in Sozi as well as in Firefox. The user interface of Sozi reacts very slowly but it works as expected.

I suppose that there is something else in your document that prevents the image from being displayed.

BTW. Even if your image file takes 7MB on disk, it is likely that it take several hundred megabytes in memory when loaded in the editor or in the web browser.

**Comment by senshu** [comment] 2018-06-09 08:10
@joha1 The issue is 3 years old and no additional info was provided to help me reproduce the problem. Closing.

**Closed by senshu** 2018-06-09 08:10 UTC
Labels: bug, unconfirmed
