### ISSUE TITLE
Grouped Elements do not show up in sozi

### ISSUE THREAD

**Issue by ghost** [senshu/Sozi#368] opened 2016-05-23 14:13 UTC
I LOVE sozi! Thanks a lot for it!
Sadly there are some "rough edges"
If I open the attached SVG in inkscape there is a wolf at the top of the image.
In sozi this (and others) are missing, compare screenshot
![missingwolf](https://cloud.githubusercontent.com/assets/13524321/15473588/fa95a610-2100-11e6-9edd-8495e20da576.png)
zipped source svg attached
It may well be user error but I could not find out what I could have done wrong...
[svg.zip](https://github.com/senshu/Sozi/files/277622/svg.zip)

**Comment by bsoun** [comment] 2016-05-24 19:30
Hi, your wolf is embed in a 
```
<svg:switch><svg:foreignObject>
```

I'm not sure ```<svg:swith>``` is supported by inkscape, you should ungroup. 
If you ungroup **[CTRL]+[SHIFT]+[G]**, twice, the svg:switch disappear.

**Comment by hubslave** [comment] 2016-05-25 13:08
I can confirm that Indeed, ungrouping solves my problem. Thanks a lot @bsoun 
I will change the issue to reflect that handling grouped objects in sozi would probably be a good idea.

**Comment by hubslave** [comment] 2016-05-25 13:10
Personally I think it would be better to show grouped elements, or at least inform the user that there are elements inside the svg that can not be handle by sozi (plus provide hints what could help, e.g. ungrouping)

**Comment by bsoun** [comment] 2016-05-25 19:02
The grouped elements are shown in the sozi, in your particular case it's due to the switch tag (perhaps not generated by inkscape ?). I think, sozi is just an animation tool. Personaly, with sozi 16, I keep inkscape open to change some elements of my svg, and with sozi I do only the animation part.

**Comment by senshu** [comment] 2016-05-25 19:52
> I think, sozi is just an animation tool

Yes. As explained here: http://sozi.baierouge.fr/pages/faq.html (Some graphics do not render correctly in Sozi)

Before reporting an issue, please make sure that your SVG document displays correctly in a web browser. If it does not, then the problem is not related to Sozi.

**Comment by hubslave** [comment] 2016-05-27 12:37
If you think that this issue is reasonably well solved by the FAQ, pleae feel free to close this issue.
As I have changed the original file I can no longer be sure if it worked in a browser or not.
I did however build a test file ( zip attached) which works in chrome and is not shown in sozi.

[Test.zip](https://github.com/senshu/Sozi/files/286458/Test.zip)

**Comment by senshu** [comment] 2017-01-28 13:13
Your document contained a group that was exported from Adobe Illustrator. This group was incorrectly imported into the user interface of Sozi. I have just pushed a fix.

**Closed** 2017-03-25 18:12 UTC
Labels: done
