### ISSUE TITLE
bottom half of slides are blank when viewed in chrome

### ISSUE THREAD

**Issue by droundy** [senshu/Sozi#380] opened 2017-01-11 14:02 UTC
Describe your problem or propose a new feature in the following sections.
Keep the headings and replace the paragraphs with your own text.

### Summary of your problem or feature request

When I view my presentation in chrome, the bottom half of the screen is white.  It views fine in firefox.

### Version of Sozi and other relevant software

* Which version of Sozi are you using? 16.02.141048
* Which drawing software did you use? Inkscape 0.91
* On which platform? Debian testing
* If your problem happens when playing a presentation, which browsers have you tried? Firefox 45.6.0esr (works fine), Chrome 55 (shows problem)

### Steps to reproduce the problem

I opened an SVG created with an older version of Sozi (an inkscape plugin version).  It converted fine, but then didn't look right in chrome.  I'll attach the files:

[testcase.zip](https://github.com/senshu/Sozi/files/699048/testcase.zip)

### Expected behavior

The presentation should fill the screen.

### Observed behavior

Only the upper half of the screen contains presentation content, which is truncated.  I presume there is something unportable in the javascript.

**Comment by senshu** [comment] 2017-02-04 09:41
I could not reproduce the issue. As far as I can tell, Chromium 55.0.2883.87 for Ubuntu shows your presentation correctly.

**Comment by senshu** [comment] 2017-11-19 16:07
I'm closing this issue since I cannot reproduce it. Please feel free to reopen it if it is still relevant with the latest versions of Sozi and Chrome.

**Closed by senshu** 2017-11-19 16:07 UTC
Labels: bug, unconfirmed
