### ISSUE TITLE
Sozi 15.05 preview: Issue playing animation FF/Chromium

### ISSUE THREAD

**Issue by Moini** [senshu/Sozi#290] opened 2015-05-16 23:38 UTC
Hi again ;),

I just played around with layer opacity and simple translation (see files here: https://gist.github.com/Moini/8bf78c5b577e917ea3da ).

The problem now is, that when I click into the running animation, I get an infinite loop (? I think), which can be stopped by clicking on the number in the top left corner.
(The animation just goes crazy, the numbers roll from 1 to 6, it zooms in and shakes... and cpu load goes up)
The animation is supposed to be 'fluent' with timeouts of 0 seconds (maybe the cause of the problem?).

This happens with both current Firefox and Chromium 41.0.2272.76 on Linux Mint 17.1 64bit.

**Comment by senshu** [comment] 2015-05-18 07:10
I could not reproduce the problem with Firefox 38 and Chromium 41.0.2272.76 on Ubuntu 14.04 64-bit.
The animations work smoothly with the expected timing.

> The animation is supposed to be 'fluent' with timeouts of 0 seconds

Yes. Do you observe a different behavior when you set a higher timeout value?

**Comment by Moini** [comment] 2015-05-18 15:50
Yes. Setting the timeout to something else stops this crazy behaviour for me.

For me, it happens *almost* every time I click into the animation (with the 0 timeout version). 
I'd love to record a video... ;)
FF tells me that the JS log was deactivated by a script, so I don't know how to get more info for you. Can you use a 'profile.json' file created by the FF runtime analyzer?

**Comment by senshu** [comment] 2015-05-21 19:52
I have pushed a fix for this issue. You can try build 15.05.212125 from
https://drive.google.com/open?id=0ByRUreHgekjMWG9teGM2dE8wck0&authuser=0

**Comment by Moini** [comment] 2015-05-21 20:11
Yay! It was enough to only save the file again :) 
And you also removed that zooming out on click. No more dizziness and crazy shaking :D
Thanks!

**Closed** 2015-06-30 20:04 UTC
Labels: bug, done, Player, Sozi 15
