### ISSUE TITLE
Layers seem to move between slides

### ISSUE THREAD

**Issue by andemil** [senshu/Sozi#295] opened 2015-06-02 13:13 UTC
Hi,

I have the following issue with Sozi 15: I have several layers that I am switching between in my presentation. It seems that Sozi is moving the layers relative to each other between slides. You can see this in the following example:
http://content.wuala.com/contents/andemil/public/embedding.sozi.html.zip
After arriving at slide nr 10 (but also before) the layers have significantly moved, so that the overall picture looks very different from the original.

Is there some way to prevent this?

Cheers,
/Andreas

**Comment by senshu** [comment] 2015-06-03 07:37
As far as I can see, this is the result of the transformations that you applied to the layers of your document.
In a given frame, if you move one layer differently from another, they will not restore their relative positions automatically.

**Comment by andemil** [comment] 2015-06-03 08:03
Thanks for the explanation! It does make sense since I did move around and scale some parts in the svg document. However to me this seems like quite a counterintuitive behaviour of Sozi. After all, in the original svg file everything is still aligned correctly. 

Does this mean that I need to redo the presentation each time I change something in the svg file? Or is there maybe a way to get around this? Could I for instance for every slide choose the same reference element on a specific layer to which everything else remains invariant?

Actually this is related to something that I noticed before, and maybe I could bring this up here as a feature request: if in Sozi I move, zoom, or rotate a layer there is no way to go back except for the undo button. It would be great to have a reset button which realigns all layers.

Cheers,
/Andreas

**Comment by senshu** [comment] 2015-06-03 13:56
> After all, in the original svg file everything is still aligned correctly.

Sozi allows layers to move independently, so if you want to keep things aligned, you must take care to always apply the same transformations to all layers.

> Does this mean that I need to redo the presentation each time I change something in the svg file?

No. The transformation applied to a layer in a given frame is relative to a reference element. If the reference element moves, then the editor will move the layer accordingly.

In my own presentations, I often add rectangles that serve only as reference elements. They can help align layers precisely. Those rectangles can be hidden using the "Hide element" button in the editor.

> It would be great to have a reset button which realigns all layers.

I understand. I will pan this for a future release.

**Comment by clement-moulin-frier** [comment] 2015-10-08 14:02
Hi everyone,

Sozi 15 is an awesome piece of software, I love it.

The only problem I have for the time being is similar to the one raised in this issue: when we move layers in a given frame of the sozi editor and then add a new layer in the svg, there is no way to reproduce the same move for that new layer so that everything is kept aligned. 
This is not a big issue if the move was only applied in one frame, but it becomes problematic when you spend time tuning a complex animation and then want to add new layer. It seems that the whole animation has to be redone if you want to keep layers aligned. Can you please confirm it is the case or let me know if I misunderstood something?

Thanks again for all this work

**Comment by jahagirdar** [comment] 2016-04-12 17:46
Similar problem here.
I am drawing a complex diagram using YEd and exporting it as an SVG file. While working on the svg file in Sozi if I add some new text or node and re export the svg file, all my frames are reset and I have to restart the presentation from scratch.
I wish there was some way for the tool to remember the zoom level of each frame and its position with respect to a key element in the frame.

**Comment by senshu** [comment] 2016-04-12 18:32
> Similar problem here.

@jahagirdar I don't see how your problem is similar to what the other posters described. I would prefer that you open a new issue.

> I wish there was some way for the tool to remember the zoom level of each frame and its position with respect to a key element in the frame.

This is exactly how Sozi works. If you reopen the same SVG, Sozi should remember the geometry of all frames even if some elements have moved. However, it requires that the *key elements* are still there and that they have the same identifier.

If I understand your situation correctly, it seems that YEd does not assign the same ids to the SVG elements when you reexport your diagram.

**Comment by senshu** [comment] 2016-04-12 19:16
I have tried yEd and actually it does not assign ids to the generated SVG elements.
There is no easy way for Sozi to keep track of *key elements*.

**Comment by jahagirdar** [comment] 2016-04-13 17:50
Thanks, I pointed the developer of yEd to this discussion at http://yed.yworks.com/support/qa/9326/assign-id-to-elements-during-svg-export-for-interop-with-sozi?show=9327#a9327
their response seems to indicate that the issue is with apache baitik...
sorry for posting on an technically unrelated thread...

**Comment by senshu** [comment] 2017-05-27 13:32
Fixed in 8158514472cf480a895d423ccfc293b97cd5e178

**Closed** 2017-07-02 08:25 UTC
Labels: done, Editor, feature
