### ISSUE TITLE
Layer alignement in many-resolution

### ISSUE THREAD

**Issue by vallsv** [senshu/Sozi#457] opened 2019-05-15 12:08 UTC
Hi, I notice that alignment of many layers looks to be resolution dependant.

I was using sozi release 19.04 on Windows.

In 16:9 or in 4:3 the slide result is not the same. Then it can make troubles.

I guess it is because the alignment is done using a corner. I don't check the code. Maybe using the center to views as reference could make the result resolution independent.

**Comment by senshu** [comment] 2019-05-15 18:18
Thanks for submitting this report.

Next time, it would be great if you could fill the issue template with the requested information, especially the section "Steps to reproduce the problem".

Unfortunately, your report is too vague and I really don't know what you expect from me: "it can make troubles" does not clearly describe the alignment differences that you observe and why you consider them as a problem.

Please provide an example that could help me understand.

**Comment by vallsv** [comment] 2019-05-16 07:47
I can send screenshots want i have time if you like .
Anyway, if you have 2 layers that you have moved to compose a scene, if you display it on a web browser and change the aspect ratio, objects of the scene will move. As result the final composition will not be the one you have composed. Which is not what you expect.

**Comment by senshu** [comment] 2019-05-16 08:50
> Anyway, if you have 2 layers that you have moved to compose a scene, if you display it on a web browser and change the aspect ratio, objects of the scene will move

In all my tests, changing the aspect ratio preserves the relative placement of all layers.
If it doesn't work as expected for you, I need to understand the specific actions that you performed to make the problem happen.

It is difficult to solve an issue that I can't reproduce. A screenshot will not be sufficient.

**Comment by vallsv** [comment] 2019-05-16 09:04
I guess is about the scale. I have to check.

**Comment by senshu** [comment] 2019-11-24 14:54
I'm closing this issue. If you still have this problem, please provide enough details to help me diagnose and fix it.

**Closed by senshu** 2019-11-24 14:54 UTC
Labels: bug, information-needed
