### ISSUE TITLE
Sozi with dualhead displays?!

### ISSUE THREAD

**Issue by zenny** [senshu/Sozi#323] opened 2015-10-25 10:58 UTC
Hi,

Sozi is nice, but it lacks a very important feature for use in pro-presentation. Dualhead projection of notes and slides on one and the mere presentation on other head. pdf-presenter-console (pdffpc) can do that. Besides the timer aspects are missing, too. Is there any plan to implement these into sozi? 

Merci beaucoup.

**Comment by senshu** [comment] 2015-10-25 14:09
There is already a feature request for a presenter console: #211 
An implementation is currently in development here: https://github.com/kai-wegner/catchi

**Comment by zenny** [comment] 2015-10-25 15:41
Thanks,

But I am getting an warnings and errors from the start on:

$ npm install
npm WARN package.json Sozi@15.05.12 No license field.
npm WARN package.json Dependency 'nunjucks' exists in both
dependencies and devDependencies, using 'nunjucks@^1.3.0' from
dependencies
npm WARN unmet dependency
/home/zenny/Downloads/Sozi/node_modules/grunt-browserify/node_modules/browserify
requires glob@'^4.0.5' but will load
npm WARN unmet dependency
/home/zenny/Downloads/Sozi/node_modules/grunt-browserify/node_modules/glob,
npm WARN unmet dependency which is version 5.0.15
npm WARN unmet dependency
/home/zenny/Downloads/Sozi/node_modules/grunt-browserify/node_modules/watchify/node_modules/browserify
requires glob@'^4.0.5' but will load
npm WARN unmet dependency
/home/zenny/Downloads/Sozi/node_modules/grunt-browserify/node_modules/glob,
npm WARN unmet dependency which is version 5.0.15
npm WARN unmet dependency
/home/zenny/Downloads/Sozi/node_modules/grunt-browserify/node_modules/watchify/node_modules/browserify
requires through2@'^1.0.0' but will load
npm WARN unmet dependency
/home/zenny/Downloads/Sozi/node_modules/grunt-browserify/node_modules/watchify/node_modules/through2,
npm WARN unmet dependency which is version 0.6.5

**Comment by senshu** [comment] 2015-10-25 17:20
> But I am getting an warnings and errors from the start on:

I don't see the connection with my previous message. Why are you trying to rebuild Sozi?

**Comment by zenny** [comment] 2015-10-25 17:23
Oh, maybe there is a misunderstanding on my part. I am trying to build sozi to try on. I am aware of the inkscape extension, but not the node.js part. Just following the installation instruction found in the README.md file.

Do you mean that sozi can run on it's own without building?

**Comment by senshu** [comment] 2015-10-25 17:25
> Do you mean that sozi can run on it's own without building?

I already built it for you :-)
https://github.com/senshu/Sozi/releases

**Comment by zenny** [comment] 2015-10-26 05:56
On 10/25/15, Guillaume Savaton <notifications@github.com> wrote:
>> Do you mean that sozi can run on it's own without building?
>
> I already built it for you :-)
> https://github.com/senshu/Sozi/releases


Fantastic.

But is it necessary to run several instances of Sozi to run several
svg files. I meant without killing the entire Sozi processes, can one
not load another presentation as a new one?

Could not figure one! If I missed something let me know. There is not
top menu bar (like File-Edit-View--etc.) in the 64bit linux binaries
that I downloaded, fyi.

**Comment by roggan87** [comment] 2015-10-26 07:50
zenny: also read [my comment on #211](https://github.com/senshu/Sozi/issues/211#issuecomment-151046033).

**Comment by senshu** [comment] 2016-02-21 16:18
Closing as duplicate of #211

**Closed by senshu** 2016-02-21 16:18 UTC
