### ISSUE TITLE
Animation speed in Sozi13 versus Sozi16

### ISSUE THREAD

**Issue by ejvindh** [senshu/Sozi#353] opened 2016-03-09 19:56 UTC
Hi,
In my transition from the old Sozi13 to Sozi16 I've previously talked about that the animations now tend to be less smooth:
https://github.com/senshu/Sozi/issues/282

In the previous example, it turned out that I was wrong. I have, however, stumbled upon a new case in which the problem is more significant. In this zip-file you will find a svg-file that contains the old Sozi13 file, and a html-file with the import into Sozi16 (made with build: Sozi-16.01.221903-linux64). It is the transition from slide 2-3 that demonstrates the issue most clearly.

I realize that with this case I'm quite hard on the animation-motor. And it is by no means a show-stopper for me personally (with the tools for handling layers I will find alternative ways of making invisible text turn up).

I just thought that it might serve as a case for you, if you at some point want to finetune the animation motor.
[Sozi.zip](https://github.com/senshu/Sozi/files/165968/Sozi.zip)

**Comment by senshu** [comment] 2018-06-01 19:33
I'm coming back to this issue because I have received several reports about regressions in animation smoothness. Users tend to agree that Sozi 13 and 15 performed better that more recent versions.

In your example with Firefox 59, I do not see any significant difference between the presentations created with Sozi 13 and 16. Do you consider that this issue should be investigated further?

**Comment by ejvindh** [comment] 2018-06-04 06:31
I can confirm that with the present-day javascript engines of both Firefox and Chrome-based browsers, the problem seems to have vanished. I cannot reproduce the problem with the attached example anymore.

**Comment by senshu** [comment] 2018-06-04 20:54
OK. Thanks.
I will close this issue. There are other similar performance issues but they concern the editor, not the player.

**Closed by senshu** 2018-06-04 20:54 UTC
Labels: Player, bug
