### ISSUE TITLE
Cannot install on Xubuntu 16.04

### ISSUE THREAD

**Issue by Aisyk** [senshu/Sozi#412] opened 2017-12-04 15:00 UTC
Hi,

The installation of Sozi with this package Sozi-17.11.191151-linux-x64 and source code don't work on Xubuntu 16.04. I've follow the README.md instructions.

Here is the errors : 
From Source code : 
```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1
```
From install.sh : 
```
install: impossible d'évaluer '/home/USER/Sozi/installation-assets/linux/../install/sozi.png': Aucun fichier ou dossier de ce type 
install: impossible d'évaluer '/home/USER/Sozi/installation-assets/linux/../install/sozi.desktop': Aucun fichier ou dossier de ce type 
Warning in file "/usr/share/applications/displaycal-vrml-to-x3d-converter.desktop": usage of MIME type "x-world/x-vrml" is discouraged (the use of "x-world" as media type is strongly discouraged in favor of a subtype of the "application" media type)
```

From install.sh from archive of Sozi : 

```
sudo /home/USER/Téléchargements/Sozi-17.11.191151-linux-x64/install/install.sh
Warning in file "/usr/share/applications/displaycal-vrml-to-x3d-converter.desktop": usage of MIME type "x-world/x-vrml" is discouraged (the use of "x-world" as media type is strongly discouraged in favor of a subtype of the "application" media type)
```

**Comment by senshu** [comment] 2017-12-04 17:59
I cannot reproduce the issue without the exact sequence of commands that you typed.
Specifically, I don't know in which folder you ran `install.sh` the first time.

As far as I can tell, warnings can be ignored.
The last execution of `install.sh` seems OK for me.

In the end, is Sozi installed and does it work?

**Comment by Aisyk** [comment] 2017-12-04 23:15
Hi,

Commands i've ran : 
`git clone git://github.com/senshu/Sozi.git`
`sudo apt install nodejs nodejs-legacy npm wine`
`sudo npm install`
Copying Droid Fonts 
    Droid Sans as vendor/DroidSans/DroidSans.eot|ttf and vendor/DroidSans/DroidSans-Bold.eot|ttf

-> Sozi

**Comment by Aisyk** [comment] 2017-12-04 23:26
More precisions, i've tryed to install with another Ubuntu 16.04 Gnome Edition, when i type `npm install`, there theses errors : 
```
 npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated coffee-script@1.10.0: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
loadDep:uuid → resolveWit ▄ ╢███████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
loadDep:sanitize-filename ▌ ╢██████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm WARN prefer global coffee-script@1.10.0 should be installed with -g
npm WARN prefer global jshint@2.8.0 should be installed with -g
npm WARN prefer global node-gyp@3.6.2 should be installed with -g
```

**Comment by senshu** [comment] 2017-12-05 11:06
> Commands i've ran :
> git clone git://github.com/senshu/Sozi.git
> sudo apt install nodejs nodejs-legacy npm wine
> sudo npm install
> Copying Droid Fonts

I don't see the following commands in your answer:

```
sudo npm install bower grunt-cli -g
bower install
grunt
```

`grunt` builds the Sozi application. The result is in the `dist` folder.

> The first time i've run install.sh i was in this folder (which created by git) : /home/USER/Sozi/

As explained in the README, the `install.sh` script must be run from the `install` folder after unzipping a Sozi archive.

> when i type npm install, there are theses errors :

I don't see error messages. Only warnings.
For the moment, we will ignore them.

**Comment by Aisyk** [comment] 2017-12-05 11:34
Hi,

After typing the commands, 
`sudo npm install bower grunt-cli -g`
`bower install`
`grunt `
i have the following error : 
`Loading "Gruntfile.js" tasks...ERROR`
`>> TypeError: buildConfig.installable.includes is not a function`
`Warning: Task "default" not found. Use --force to continue.`
`Aborted due to warnings.`

No `dist` folder in my installation.

**Comment by senshu** [comment] 2017-12-05 12:12
> Loading "Gruntfile.js" tasks...ERROR

It seems that your version of node.js is older than mine.

I have pushed a modified `Gruntfile.js` to avoid this error.
Run `git pull` from `home/USER/Sozi`, and then `grunt` again.

> No dist folder in my installation.

It will be created during the build process.

**Comment by Aisyk** [comment] 2017-12-05 13:32
Hi,

After theses commands, another error : 
`sozi: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory`

**Comment by Aisyk** [comment] 2017-12-05 13:36
After installing : 
`sudo apt-get install libgtk2.0-0:i386`
I've got theses errors : 
`sozi: error while loading shared libraries: libXtst.so.6: cannot open shared object file: No such file or director`
How many dependencies i need to install ? This cannot be installed with the installation process ?

**Comment by senshu** [comment] 2017-12-05 20:44
> sudo apt-get install libgtk2.0-0:i386

Are you running a 32-bit OS? If not, you should remove the "i386" suffix:

```
sudo apt-get install libgtk2.0-0
```

If you are using XUbuntu, it is not clear why this library is not already installed.
I never had to install it myself and you are the first to report this problem.

I have added the full list of libraries to install [at the end of the README](https://github.com/senshu/Sozi#install). Run the given `sudo apt install ...` command in a terminal and it should be OK.

**Comment by Aisyk** [comment] 2017-12-07 01:27
I'm running a 64bits system.
I have already `libgtk2.0-0`. Error demands a 32bit library.

The list is great but isn't easily copiable in a terminal, all lines with "/"... :/ this is not very enjoyable to install them.

**Comment by senshu** [comment] 2017-12-07 07:02
> I have already libgtk2.0-0. Error demands a 32bit library.

The error message you pasted was:

```
sozi: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
```

I don't see anything about 32-bit here. Was there another message that you forgot to mention?

I am running Ubuntu 16.04 64-bit. On my system, only the 64-bit libgtk is installed and Sozi runs fine.

> The list is great but isn't easily copiable in a terminal,

I don't understand. Just copy-paste the whole command.

**Comment by senshu** [comment] 2017-12-07 07:04
Just in case : in terminals, you can paste with Ctrl-Shift-V.

**Comment by Aisyk** [comment] 2017-12-07 14:24
> I don't see anything about 32-bit here. Was there another message that you forgot to mention?
In my researches, the libgtk-x11-2.0-0 was a 32bits library, part of ia32-libs package. https://www.linuxquestions.org/questions/linux-software-2/error-while-loading-shared-libraries-libgtk-x11-2-0-so-0-cannot-738695/

I have all the dependancies you mention in the README.
```
 sudo apt install     libasound2     libatk1.0-0     libavahi-client3     libavahi-common3     libc6 libcairo2     libcomerr2     libcups2     libdatrie1     libdbus-1-3     libdbus-glib-1-2     libexpat1     libffi6     libfontconfig1     libfreetype6     libgcc1     libgconf-2-4     libgcrypt20     libgdk-pixbuf2.0-0     libglib2.0-0     libgmp10     libgnutls30     libgpg-error0     libgraphite2-3     libgssapi-krb5-2     libgtk2.0-0     libharfbuzz0b     libhogweed4     libidn11     libk5crypto3     libkeyutils1     libkrb5-3     libkrb5support0     liblzma5     libnettle6     libnspr4     libnss3     libp11-kit0     libpango-1.0-0     libpangocairo-1.0-0     libpangoft2-1.0-0     libpcre3     libpixman-1-0     libpng12-0     libselinux1     libstdc++6     libsystemd0     libtasn1-6     libthai0     libx11-6     libx11-xcb1     libxau6     libxcb1     libxcb-render0     libxcb-shm0     libxcomposite1     libxcursor1     libxdamage1     libxdmcp6     libxext6     libxfixes3     libxi6     libxinerama1     libxrandr2     libxrender1     libxss1     libxtst6     zlib1g
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
libasound2 is already the newest version (1.1.0-0ubuntu1).
libatk1.0-0 is already the newest version (2.18.0-1).
libavahi-client3 is already the newest version (0.6.32~rc+dfsg-1ubuntu2).
libavahi-common3 is already the newest version (0.6.32~rc+dfsg-1ubuntu2).
libcairo2 is already the newest version (1.14.6-1).
libcomerr2 is already the newest version (1.42.13-1ubuntu1).
libdatrie1 is already the newest version (0.2.10-2).
libdbus-glib-1-2 is already the newest version (0.106-1).
libffi6 is already the newest version (3.2.1-4).
libgcc1 is already the newest version (1:6.0.1-0ubuntu1).
libgconf-2-4 is already the newest version (3.2.6-3ubuntu6).
libgmp10 is already the newest version (2:6.1.0+dfsg-2).
libgpg-error0 is already the newest version (1.21-2ubuntu1).
libkeyutils1 is already the newest version (1.5.9-8ubuntu1).
liblzma5 is already the newest version (5.1.1alpha+20120614-2ubuntu2).
libpango-1.0-0 is already the newest version (1.38.1-1).
libpangocairo-1.0-0 is already the newest version (1.38.1-1).
libpangoft2-1.0-0 is already the newest version (1.38.1-1).
libpcre3 is already the newest version (2:8.38-3.1).
libpixman-1-0 is already the newest version (0.33.6-1).
libpng12-0 is already the newest version (1.2.54-1ubuntu1).
libselinux1 is already the newest version (2.4-3build2).
libthai0 is already the newest version (0.1.24-2).
libx11-6 is already the newest version (2:1.6.3-1ubuntu2).
libx11-xcb1 is already the newest version (2:1.6.3-1ubuntu2).
libxau6 is already the newest version (1:1.0.8-1).
libxcb-render0 is already the newest version (1.11.1-1ubuntu1).
libxcb-shm0 is already the newest version (1.11.1-1ubuntu1).
libxcb1 is already the newest version (1.11.1-1ubuntu1).
libxcomposite1 is already the newest version (1:0.4.4-1).
libxdamage1 is already the newest version (1:1.1.4-2).
libxdmcp6 is already the newest version (1:1.1.2-1.1).
libxext6 is already the newest version (2:1.3.3-1).
libxfixes3 is already the newest version (1:5.0.1-2).
libxi6 is already the newest version (2:1.7.6-1).
libxinerama1 is already the newest version (2:1.1.3-1).
libxrandr2 is already the newest version (2:1.5.0-1).
libxrender1 is already the newest version (1:0.9.9-0ubuntu1).
libxss1 is already the newest version (1:1.2.2-1).
libxtst6 is already the newest version (2:1.2.2-1).
libc6 is already the newest version (2.23-0ubuntu9).
libcups2 is already the newest version (2.1.3-4ubuntu0.3).
libdbus-1-3 is already the newest version (1.10.6-1ubuntu3.3).
libexpat1 is already the newest version (2.1.0-7ubuntu0.16.04.3).
libfontconfig1 is already the newest version (2.11.94-0ubuntu1.1).
libfreetype6 is already the newest version (2.6.1-0.1ubuntu2.3).
libgcrypt20 is already the newest version (1.6.5-2ubuntu0.3).
libgdk-pixbuf2.0-0 is already the newest version (2.32.2-1ubuntu1.3).
libglib2.0-0 is already the newest version (2.48.2-0ubuntu1).
libgnutls30 is already the newest version (3.4.10-4ubuntu1.4).
libgraphite2-3 is already the newest version (1.3.10-0ubuntu0.16.04.1).
libgssapi-krb5-2 is already the newest version (1.13.2+dfsg-5ubuntu2).
libgtk2.0-0 is already the newest version (2.24.30-1ubuntu1.16.04.2).
libharfbuzz0b is already the newest version (1.0.1-1ubuntu0.1).
libhogweed4 is already the newest version (3.2-1ubuntu0.16.04.1).
libidn11 is already the newest version (1.32-3ubuntu1.2).
libk5crypto3 is already the newest version (1.13.2+dfsg-5ubuntu2).
libkrb5-3 is already the newest version (1.13.2+dfsg-5ubuntu2).
libkrb5support0 is already the newest version (1.13.2+dfsg-5ubuntu2).
libnettle6 is already the newest version (3.2-1ubuntu0.16.04.1).
libnspr4 is already the newest version (2:4.13.1-0ubuntu0.16.04.1).
libnss3 is already the newest version (2:3.28.4-0ubuntu0.16.04.3).
libp11-kit0 is already the newest version (0.23.2-5~ubuntu16.04.1).
libstdc++6 is already the newest version (5.4.0-6ubuntu1~16.04.5).
libsystemd0 is already the newest version (229-4ubuntu21).
libtasn1-6 is already the newest version (4.7-3ubuntu0.16.04.2).
libxcursor1 is already the newest version (1:1.1.14-1ubuntu0.16.04.1).
zlib1g is already the newest version (1:1.2.8.dfsg-2ubuntu4.1).
```

**Comment by senshu** [comment] 2017-12-07 15:08
> In my researches, the libgtk-x11-2.0-0 was a 32bits library, part of ia32-libs package. https://www.linuxquestions.org/questions/linux-software-2/error-while-loading-shared-libraries-libgtk-x11-2-0-so-0-cannot-738695/

In that discussion, the user attempted to run Firefox on a 64-bit system. In 2009, I think that Firefox was only built for 32-bit architectures, so the system complained that it needed libgtk2 32-bit.

> I have all the dependancies you mention in the README.

Can you execute the following command and tell me what you get?

```
file /opt/Sozi/sozi
```

**Comment by Aisyk** [comment] 2017-12-07 15:14
Ok, that's it !

When i type sozi it runs.
thanks for your help !

**Comment by senshu** [comment] 2017-12-08 07:53
Do you think that we can close this issue?

**Comment by Aisyk** [comment] 2017-12-10 15:40
Yes, we can, thanks for your help.

**Closed** 2017-12-10 16:58 UTC
Labels: bug, installation, unconfirmed
