### ISSUE TITLE
Nothing happens when clicking on 'Information' button

### ISSUE THREAD

**Issue by Codain** [senshu/Sozi#446] opened 2018-11-14 11:57 UTC
Using Sozi 18.04 on Windows 10, there is an `Information` button next to `Preferences`. When I click on it nothing happens (or at least I can't see any anything happening).

**Comment by senshu** [comment] 2018-11-14 12:54
The information button should display a notification with the version number of Sozi.
Unfortunately, none of my computers run Windows, so I can't reproduce the issue.

According to [the Electron documentation](https://electronjs.org/docs/tutorial/notifications), I understand that Sozi needs additional setup to use notifications in Windows 10.

**Comment by senshu** [comment] 2020-01-01 16:31
Fixed in commit f1c276c498dc912a137e87d61509453e8e960931 
Sozi no longer uses the OS notifications.

**Closed** 2020-01-06 10:00 UTC
Labels: bug, done
