### ISSUE TITLE
reload SVG break sozi editor 17.11

### ISSUE THREAD

**Issue by as3mbus** [senshu/Sozi#415] opened 2018-01-09 06:18 UTC
### Summary of your problem or feature request

sozi is breaking when reloading svg and reopenning svg results in unmodified looks
workaround that i did is deleting html and json file resulting in recreating each frame from start 

### Version of Sozi and other relevant software

* Which version of Sozi are you using? Sozi 17.11
* Which drawing software did you use? Inkscape 0.92.2
* On which platform? Ubuntu Linux 16.04 64 Bit
* If your problem happens when playing a presentation, which browsers have you tried? 

### Steps to reproduce the problem

- create sozi from existing svg.
- add some object or graphic
- reload svg
- it's not reloading but it break sozi instead(button not working, preview cant be moved anymore etc)

### Expected behavior

it should reload the svg so i dont need to recreate every frame again

### Observed behavior

it's breaking sozi when i press reload svg, and reopenning sozi with same file is displaying old svg (especially size modification not applied)

**Comment by senshu** [comment] 2018-01-10 21:06
Thanks for reporting.
This issue is a duplicate of #411 and is already fixed in the development version.

You can try Sozi 17.12 from https://drive.google.com/drive/folders/0ByRUreHgekjMWG9teGM2dE8wck0 and tell me if it works for you.

**Closed** 2018-02-07 19:32 UTC
Labels: Editor, bug, done
